# This workflow is used to test the GitHub action

name: Test shareableviz-action

permissions:
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "VERSION"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Create a Kedro Project and install project dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "kedro>=0.19.3"
          kedro new --starter=spaceflights-pandas-viz --name=demo-project
          cd demo-project
          pip install -r requirements.txt
      - name: Deploy Kedro-Viz to GH Pages
        uses: ./
        with:
          telemetry_consent: false
          project_path: 'demo-project'
          publishing_source: 'workflow'
